### ISSUE TITLE
Chrome V66 placeholder doesn't dissapear on-focus

### ISSUE THREAD

**Issue by Valerz** [geminilabs/float-labels.js#28] opened 2018-08-28 00:37 UTC
Hello,
With Chrome version 66 when you focus on the input field the placeholder text doesn't disappear until you start typing, however in IE11 it does.

EDIT: 
I added to css: 

.fl-form .fl-has-focus input.fl-input::-webkit-input-placeholder {
    color: #fff;
  }

Seems to have fixed it. Not sure if this is best way to go around it. 

You can close ticket if so.

**Comment by pryley** [comment] 2018-09-02 22:41
This is non-standard behaviour that is [caused by a bug in Internet Explorer 10-11](https://twitter.com/hakanson/status/479697588908613632). 

As it does not affect the functionality of Float Labels, I am closing this issue.

Please also see:
https://stackoverflow.com/questions/14445891/keep-placeholder-on-focus-in-ie10/16138480#24319798

**Closed as completed by pryley** 2018-09-02 22:41 UTC
